import { createClient, type SupabaseClient, type User } from "npm:@supabase/supabase-js@2";
function configuredOrigin(){return Deno.env.get("CITYFLOW_ALLOWED_ORIGIN")?.trim()||"*";}
export const corsHeaders={"Access-Control-Allow-Origin":configuredOrigin(),"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, idempotency-key","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS","Vary":"Origin"};
export function json(data:unknown,status=200,extra:Record<string,string>={}){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json",...extra}})}
export function error(code:string,message:string,status=400,details?:unknown){return json({error:{code,message,details:details??null}},status)}
export function options(){return new Response("ok",{headers:corsHeaders})}
export function clients(req:Request){const url=Deno.env.get("SUPABASE_URL")!;const p=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")??"{}").default;const s=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")??"{}").default;if(!p||!s)throw new Error("SUPABASE_KEYS_NOT_CONFIGURED");const auth=req.headers.get("Authorization")??"";return{userClient:createClient(url,p,{global:{headers:{Authorization:auth}}}),adminClient:createClient(url,s)}}
export async function requireUser(req:Request,c:SupabaseClient):Promise<User>{const t=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!t)throw new Error("AUTH_REQUIRED");const{data,error:ae}=await c.auth.getUser(t);if(ae||!data.user)throw new Error("AUTH_INVALID");return data.user}
export async function body(req:Request,maxBytes=1024*1024){const length=Number(req.headers.get("content-length")??"0");if(length>maxBytes)throw new Error("PAYLOAD_TOO_LARGE");try{const text=await req.text();if(new TextEncoder().encode(text).byteLength>maxBytes)throw new Error("PAYLOAD_TOO_LARGE");return JSON.parse(text)}catch(e){if(e instanceof Error&&e.message==="PAYLOAD_TOO_LARGE")throw e;throw new Error("INVALID_JSON")}}
export function mapError(e:unknown){const m=e instanceof Error?e.message:String(e);if(m==="AUTH_REQUIRED")return error("AUTH_REQUIRED","Authentication required",401);if(m==="AUTH_INVALID")return error("AUTH_INVALID","Invalid authentication",401);if(m==="INVALID_JSON")return error("INVALID_JSON","Invalid JSON body",400);if(m==="PAYLOAD_TOO_LARGE")return error("PAYLOAD_TOO_LARGE","Request body too large",413);if(m==="SUPABASE_KEYS_NOT_CONFIGURED")return error("SERVER_MISCONFIGURED","Server authentication keys are not configured",503);return error("INTERNAL_ERROR","Unexpected server error",500)}